export const prueba = [
  {
    profileImage:
      "https://www.tuexperto.com/wp-content/uploads/2015/07/perfil_01.jpg",
    name: "Chiringuito",
    lastName: "Vega",
    birthDate: "2022/04/25",
    nacionality: "Argentino",
    country: "Argentina",
    timeZone: "GTM -3",
    email: "chirivega@test.com",
    password: "chirivega123",
    phone: "94-2834527",
    profession: "Arquitecto",
    studies: "Titulo universitario",
    gender: "Masculino",
    rol: 'SuperAdmin'
  },
  {
    email: "fulanito.test@mail.com",
    password: "test1234",
  },
];

export const voluntario = [
  {
    profilePhoto: "https://www.tuexperto.com/wp-content/uploads/2015/07/perfil_01.jpg",
    name: "Charanguito",
    lastName: "Grillia",
    birthDate: "2022/04/26",
    nacionality: "Uruguayo",
    country: "Argentina",
    timeZone: "GTM -3",
    email: "charagrillia@test.com",
    password: "charagrillia123",
    phone: "72-68552123",
    profession: "Programador",
    studies: "Henry Bootcamp",
    gender: "Masculino",
    rol: 'Companion'
  },
  {
    profilePhoto: "https://www.tuexperto.com/wp-content/uploads/2015/07/perfil_01.jpg",
    name: "Charanguito",
    lastName: "Grillia",
    birthDate: "2022/04/26",
    nacionality: "Uruguayo",
    country: "Argentina",
    timeZone: "GTM -3",
    email: "charagrillia@test.com",
    password: "charagrillia123",
    phone: "72-68552123",
    profession: "Programador",
    studies: "Henry Bootcamp",
    gender: "Masculino",
    rol: 'Companion'
  },
  {
    profilePhoto: "https://www.tuexperto.com/wp-content/uploads/2015/07/perfil_01.jpg",
    name: "Charanguito",
    lastName: "Grillia",
    birthDate: "2022/04/26",
    nacionality: "Uruguayo",
    country: "Argentina",
    timeZone: "GTM -3",
    email: "charagrillia@test.com",
    password: "charagrillia123",
    phone: "72-68552123",
    profession: "Programador",
    studies: "Henry Bootcamp",
    gender: "Masculino",
    rol: 'Companion'
  },
  {
    profilePhoto: "https://www.tuexperto.com/wp-content/uploads/2015/07/perfil_01.jpg",
    name: "Guido",
    lastName: "Dictador",
    birthDate: "2022/05/05",
    nacionality: "Alemán",
    country: "Argentina",
    timeZone: "GTM -3",
    email: "umpaLumpa@test.com",
    password: "charagrillia123",
    phone: "72-68552123",
    profession: "Programador",
    studies: "Henry Bootcamp",
    gender: "Masculino",
    rol: 'Companion'
  },
  {
    profilePhoto: "https://www.tuexperto.com/wp-content/uploads/2015/07/perfil_01.jpg",
    name: "Remy",
    lastName: "Rata",
    birthDate: "2003/11/12",
    nacionality: "Colombiano",
    country: "Mongolia",
    timeZone: "GTM -3",
    email: "charagrillia@test.com",
    password: "charagrillia123",
    phone: "72-68552123",
    profession: "Programador",
    studies: "Henry Bootcamp",
    gender: "Masculino",
    rol: 'Companion'
  },
  {
    profilePhoto: "https://www.tuexperto.com/wp-content/uploads/2015/07/perfil_01.jpg",
    name: "Gonzalo",
    lastName: "Brito",
    birthDate: "2000/09/07",
    nacionality: "Aleman",
    country: "Italia",
    timeZone: "GTM -3",
    email: "GB@test.com",
    password: "charagrillia123",
    phone: "72-68552123",
    profession: "Programador",
    studies: "Henry Bootcamp",
    gender: "Masculino",
    rol: 'Companion'
  },
  {
    profilePhoto: "https://www.tuexperto.com/wp-content/uploads/2015/07/perfil_01.jpg",
    name: "Gonzalo",
    lastName: "Brito",
    birthDate: "2000/09/07",
    nacionality: "Aleman",
    country: "Italia",
    timeZone: "GTM -3",
    email: "GB@test.com",
    password: "charagrillia123",
    phone: "72-68552123",
    profession: "Programador",
    studies: "Henry Bootcamp",
    gender: "Masculino",
    rol: 'Companion'
  },
  {
    profilePhoto: "https://www.tuexperto.com/wp-content/uploads/2015/07/perfil_01.jpg",
    name: "Gonzalo",
    lastName: "Brito",
    birthDate: "2000/09/07",
    nacionality: "Aleman",
    country: "Italia",
    timeZone: "GTM -3",
    email: "GB@test.com",
    password: "charagrillia123",
    phone: "72-68552123",
    profession: "Programador",
    studies: "Henry Bootcamp",
    gender: "Masculino",
    rol: 'Companion'
  },
  {
    email: 'prueba.test@mail.com',
    password: 'prueba123'
  }
];
