export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT = "LOGOUT";
export const GET_ALL_COMPANIONS = "GET_ALL_COMPANIONS";
export const GET_ALL_SUPERVISORS = "GET_ALL_SUPERVISORS";
export const GET_COMPANIONS_AT_CHARGE = "GET_COMPANIONS_AT_CHARGE";
