const allCountries = [
    "Andorra",
    "Emiratos Árabes Unidos",
    "Afganistán",
    "Antigua y Barbuda",
    "Anguila",
    "Albania",
    "Armenia",
    "Angola",
    "Antártida",
    "Argentina",
    "Samoa Americana",
    "Austria",
    "Australia",
    "Aruba",
    "Islas de Åland",
    "Azerbaiyán",
    "Bosnia y Herzegovina",
    "Barbados",
    "Bangladesh",
    "Bélgica",
    "Burkina Faso",
    "Bulgaria",
    "Bahrein",
    "Burundi",
    "Benín",
    "San Bartolomé",
    "Islas Bermudas",
    "Brunéi",
    "Bolivia",
    "Bonaire, San Eustaquio y Saba",
    "Brasil",
    "Bahamas",
    "Bhután",
    "Isla Bouvet",
    "Botsuana",
    "Bielorrusia",
    "Belice",
    "Canadá",
    "Islas Cocos (Keeling)",
    "República Democrática del Congo",
    "República Centroafricana",
    "República del Congo",
    "Suiza",
    "Costa de Marfil",
    "Islas Cook",
    "Chile",
    "Camerún",
    "China",
    "Colombia",
    "Costa Rica",
    "Cuba",
    "Cabo Verde",
    "Curazao",
    "Isla de Navidad",
    "Chipre",
    "República Checa",
    "Alemania",
    "Yibuti",
    "Dinamarca",
    "Dominica",
    "República Dominicana",
    "Argelia",
    "Ecuador",
    "Estonia",
    "Egipto",
    "Sahara Occidental",
    "Eritrea",
    "España",
    "Etiopía",
    "Finlandia",
    "Fiyi",
    "Islas Malvinas",
    "Micronesia",
    "Islas Feroe",
    "Francia",
    "Gabón",
    "Reino Unido",
    "Granada",
    "Georgia",
    "Guayana Francesa",
    "Guernsey",
    "Ghana",
    "Gibraltar",
    "Groenlandia",
    "Gambia",
    "Guinea",
    "Guadalupe",
    "Guinea Ecuatorial",
    "Grecia",
    "Islas Georgias del Sur y Sandwich del Sur",
    "Guatemala",
    "Guam",
    "Guinea-Bissau",
    "Guyana",
    "Hong kong",
    "Islas Heard y McDonald",
    "Honduras",
    "Croacia",
    "Haití",
    "Hungría",
    "Indonesia",
    "Irlanda",
    "Israel",
    "Isla de Man",
    "India",
    "Territorio Británico del Océano Índico",
    "Irak",
    "Irán",
    "Islandia",
    "Italia",
    "Jersey",
    "Jamaica",
    "Jordania",
    "Japón",
    "Kenia",
    "Kirguistán",
    "Camboya",
    "Kiribati",
    "Comoras",
    "San Cristóbal y Nieves",
    "Corea del Norte",
    "Corea del Sur",
    "Kuwait",
    "Islas Caimán",
    "Kazajistán",
    "Laos",
    "Líbano",
    "Santa Lucía",
    "Liechtenstein",
    "Sri lanka",
    "Liberia",
    "Lesoto",
    "Lituania",
    "Luxemburgo",
    "Letonia",
    "Libia",
    "Marruecos",
    "Mónaco",
    "Moldavia",
    "Montenegro",
    "San Martín (Francia)",
    "Madagascar",
    "Islas Marshall",
    "Macedonia del Norte",
    "Mali",
    "Birmania",
    "Mongolia",
    "Macao",
    "Islas Marianas del Norte",
    "Martinica",
    "Mauritania",
    "Montserrat",
    "Malta",
    "Mauricio",
    "Islas Maldivas",
    "Malawi",
    "México",
    "Malasia",
    "Mozambique",
    "Namibia",
    "Nueva Caledonia",
    "Niger",
    "Isla Norfolk",
    "Nigeria",
    "Nicaragua",
    "Países Bajos",
    "Noruega",
    "Nepal",
    "Nauru",
    "Niue",
    "Nueva Zelanda",
    "Omán",
    "Panamá",
    "Perú",
    "Polinesia Francesa",
    "Papúa Nueva Guinea",
    "Filipinas",
    "Pakistán",
    "Polonia",
    "San Pedro y Miquelón",
    "Islas Pitcairn",
    "Puerto Rico",
    "Palestina",
    "Portugal",
    "Palau",
    "Paraguay",
    "Qatar",
    "Reunión",
    "Rumanía",
    "Serbia",
    "Rusia",
    "Ruanda",
    "Arabia Saudita",
    "Islas Salomón",
    "Seychelles",
    "Sudán",
    "Suecia",
    "Singapur",
    "Santa Elena",
    "Eslovenia",
    "Svalbard y Jan Mayen",
    "Eslovaquia",
    "Sierra Leona",
    "San Marino",
    "Senegal",
    "Somalia",
    "Surinám",
    "República de Sudán del Sur",
    "Santo Tomé y Príncipe",
    "El Salvador",
    "Sint Maarten",
    "Siria",
    "Swazilandia",
    "Islas Turcas y Caicos",
    "Chad",
    "Territorios Australes y Antárticas Franceses",
    "Togo",
    "Tailandia",
    "Tayikistán",
    "Tokelau",
    "Timor Oriental",
    "Turkmenistán",
    "Tunez",
    "Tonga",
    "Turquía",
    "Trinidad y Tobago",
    "Tuvalu",
    "Taiwán",
    "Tanzania",
    "Ucrania",
    "Uganda",
    "Islas Ultramarinas Menores de Estados Unidos",
    "Estados Unidos de América",
    "Uruguay",
    "Uzbekistán",
    "Ciudad del Vaticano",
    "San Vicente y las Granadinas",
    "Venezuela",
    "Islas Vírgenes Británicas",
    "Islas Vírgenes de los Estados Unidos",
    "Vietnam",
    "Vanuatu",
    "Wallis y Futuna",
    "Samoa",
    "Yemen",
    "Mayotte",
    "Sudáfrica",
    "Zambia",
    "Zimbabue"
]

export default allCountries;